
EXTRA_CFLAGS += -Idrivers/media/dvb/dvb-core/
EXTRA_CFLAGS += -Idrivers/media/platform_tab4/msm/dvb/include/

obj-$(CONFIG_DVB_MPQ) += mpq-adapter.o

mpq-adapter-y := mpq_adapter.o mpq_stream_buffer.o

