ccflags-y += -Idrivers/media/platform_tab4/msm/camera_v2
ccflags-y += -Idrivers/media/platform_tab4/msm/camera_v2/sensor/io
ccflags-y += -Idrivers/media/platform_tab4/msm/camera_v2/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += msm_actuator.o
