ccflags-y += -Idrivers/media/platform_tab4/msm/camera_v2
ccflags-y += -Idrivers/media/platform_tab4/msm/camera_v2/isp/
ccflags-y += -Idrivers/media/platform_tab4/msm/camera_v2/sensor/io
obj-$(CONFIG_MSM_CPP) += msm_cpp.o
